# Generated by Django 4.2.4 on 2023-08-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('categoria_empresa', models.CharField(choices=[('artesanato', 'Artesanato'), ('livraria', 'Livraria'), ('fast-food', 'Fast-Food')], max_length=20)),
                ('cnpj', models.CharField(max_length=18)),
                ('quitado', models.BooleanField(default=False)),
                ('stand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.stands')),
            ],
        ),
    ]
