# Generated by Django 4.2.4 on 2023-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
